function get_topics(){
let res=[];
res.push([]);
res[0].push('First love');
res[0].push('First relationship');
res[0].push('First date');
res[0].push('First kiss');
res[0].push('Holding hands');
res[0].push('First confession');
res.push([]);
res[1].push('Date');
res[1].push('Hug');
res[1].push('Kiss');
res[1].push('Holding hands');
res[1].push('Confession');
res.push([]);
res[2].push('One-way love');
res[2].push('Long-distance relationship');
res[2].push('Heart broken');
res[2].push('Love triangle relationship with his/her friends');
res[2].push('A conflicting triangle relationship you want to win');
res[2].push('Being engaged while having another boyfriend/girlfriend');
res[2].push('Having several boyfriends/girlfriends');
res[2].push('Not finding "the one"');
res.push([]);
res[3].push('Someone with good hygiene');
res[3].push('Someone with good fashion sense');
res[3].push('Someone serious');
res[3].push('Someone rich');
res[3].push('Someone smart');
res[3].push('Someone very thoughful');
res[3].push('Someone very supportive');
res[3].push('Someone who is good at anything');
res[3].push('Someone careless');
res[3].push('Someone arrogant');
res.push([]);
res[4].push('Mask');
res[4].push('Sunglasses');
res[4].push('Glasses');
res[4].push('Suit');
res[4].push('Hat');
res[4].push('Blue jeans');
res.push([]);
res[5].push('Coffee');
res[5].push('Lemon tea');
res[5].push('Milk tea');
res[5].push('Green tea');
res[5].push('Oolong tea');
res[5].push('Cocoa');
res.push([]);
res[6].push('Wine');
res[6].push('Beer');
res[6].push('Japanese sake');
res[6].push('Whisky');
res[6].push('Plum sake');
res[6].push('Coffee');
res.push([]);
res[7].push('Apple');
res[7].push('Orange');
res[7].push('Peach');
res[7].push('Pear');
res[7].push('Grape');
res[7].push('Watermelon');
res[7].push('Melon');
res[7].push('Tomato');
res[7].push('Plum');
res.push([]);
res[8].push('Chinese cabbage');
res[8].push('Cabbage');
res[8].push('Lettuce');
res[8].push('Spinach');
res[8].push('Onion');
res[8].push('Green pepper');
res.push([]);
res[9].push('Curry');
res[9].push('Beef stew');
res[9].push('Ramen');
res[9].push('Noodles');
res[9].push('Spaghetti');
res[9].push('Ravioli');
res.push([]);
res[10].push('high-speed train');
res[10].push('Local train');
res[10].push('Bus');
res[10].push('Taxi');
res[10].push('Car');
res[10].push('Bicycle');
res.push([]);
res[11].push('Ambulance');
res[11].push('Fire truck');
res[11].push('Police car');
res[11].push('Tow truck');
res[11].push('Hearse');
res.push([]);
res[12].push('Tyrannosaurus');
res[12].push('Mammoth');
res[12].push('Triceratops');
res[12].push('Pteranodon');
res[12].push('Brachiosaurus');
res[12].push('Mosasaurus');
res[12].push('Spinosaurus');
res.push([]);
res[13].push('Mammoth');
res[13].push('Elephant');
res[13].push('Hippopotamus');
res[13].push('Rhinoceros');
res[13].push('Horse');
res.push([]);
res[14].push('Wolf');
res[14].push('Dog');
res[14].push('Fox');
res[14].push('Wild dog');
res[14].push('Mouse');
res[14].push('Rabbit');
res.push([]);
res[15].push('Pigeon');
res[15].push('Sparrow');
res[15].push('Crow');
res[15].push('Owl');
res[15].push('Swallow');
res[15].push('Falcon');
res.push([]);
res[16].push('Cat');
res[16].push('Wild cat');
res[16].push('Tiger');
res[16].push('Lion');
res[16].push('Jaguar');
res[16].push('Panther');
res[16].push('Cheetah');
res[16].push('Puma');
res.push([]);
res[17].push('Dolphin');
res[17].push('Whale');
res[17].push('Killer whale');
res[17].push('Manta ray');
res[17].push('Sunfish');
res.push([]);
res[18].push('Lizard');
res[18].push('Iguana');
res[18].push('Turtle');
res[18].push('Crocodile');
res[18].push('Frog');
res.push([]);
res[19].push('Rhinoceros beetle');
res[19].push('Stag beetle');
res[19].push('Longicorn beetle');
res[19].push('Longhorn beetle');
res[19].push('Ladybug');
res[19].push('Snail');
res.push([]);
res[20].push('Cicada');
res[20].push('Cricket');
res[20].push('Bell cricket');
res[20].push('Grasshopper');
res[20].push('Mantis');
res.push([]);
res[21].push('Bee');
res[21].push('Fly');
res[21].push('Mosquito');
res[21].push('Flying ant');
res[21].push('Dragonfly');
res.push([]);
res[22].push('Buffalo');
res[22].push('Cow');
res[22].push('Horse');
res[22].push('Deer');
res[22].push('Boar');
res[22].push('Pork');
res[22].push('Sheep');
res[22].push('Bear');
res[22].push('Rabbit');
res.push([]);
res[23].push('Rose');
res[23].push('Tulip');
res[23].push('Morning glory');
res[23].push('Sunflower');
res[23].push('Pansy');
res[23].push('Margaret');
res[23].push('Sweet pea');
res[23].push('Lily');
res[23].push('Hydrangea');
res[23].push('Cosmos');
res.push([]);
res[24].push('Typhoon');
res[24].push('Thunder');
res[24].push('Tornade');
res[24].push('Windstorm');
res[24].push('Rainbow');
res[24].push('Aurora');
res.push([]);
res[25].push('River');
res[25].push('Waterfall');
res[25].push('Sea');
res[25].push('Mountain');
res[25].push('Valley');
res[25].push('Hill');
res[25].push('Lake');
res.push([]);
res[26].push('Group leader');
res[26].push('School kitchen staff');
res[26].push('Student council');
res.push([]);
res[27].push('Hiking excursion');
res[27].push('Field trip');
res[27].push('Factory tour');
res[27].push('Sports day');
res[27].push('School festival');
res[27].push('School excursion');
res[27].push('Swimming class');
res[27].push('Ski class');
res.push([]);
res[28].push('Class observation by parents');
res[28].push('Parent and child meeting');
res[28].push('Academic counseling');
res[28].push('Mock exam');
res[28].push('Class meeting');
res.push([]);
res[29].push('Pencil');
res[29].push('Highlighter pen');
res[29].push('Multi color pen');
res[29].push('mechanical pencil');
res[29].push('Ballpoint pen');
res[29].push('Red pen');
res[29].push('Brush');
res.push([]);
res[30].push('First coffee');
res[30].push('First soda');
res[30].push('First liquor');
res[30].push('First beer');
res[30].push('First French wine');
res[30].push('First breast milk');
res[30].push('First Japanese sake');
res.push([]);
res[31].push('First thunder');
res[31].push('First snow');
res[31].push('First typhoon');
res[31].push('First rain');
res[31].push('First earthquake');
res[31].push('First full moon');
res[31].push('First lunar eclipse');
res[31].push('First solar eclipse');
res[31].push('First hail storm');
res[31].push('First flowering cherry trees');
res[31].push('First heat wave');
res.push([]);
res[32].push('First spicy curry taste');
res[32].push('First mustard taste');
res[32].push('First wasabi taste');
res[32].push('First ginger taste');
res[32].push('First lemon taste');
res[32].push('First red cayenne pepper');
res.push([]);
res[33].push('Sexual appetite');
res[33].push('Appetite');
res[33].push('Wanting to sleep');
res[33].push('Wanting to pee');
res[33].push('Wanting to poo');
res[33].push('Thirst');
res.push([]);
res[34].push('School gym clothes');
res[34].push('School uniform');
res[34].push('Leotard');
res[34].push('Swim suit');
res[34].push('Lab coat');
res[34].push('Suit');
res.push([]);
res[35].push('Hiccup');
res[35].push('Cough');
res[35].push('Sneeze');
res[35].push('Runny nose');
res[35].push('Burp');
res[35].push('Yawn');
res[35].push('Tinnitus');
res.push([]);
res[36].push('Chocolate eclairs');
res[36].push('Cream puffs');
res[36].push('Cream-stuffed pastries');
res[36].push('Ice cream');
res.push([]);
res[37].push('Permanent makeup');
res[37].push('Permanent hair removal');
res[37].push('Curly hair permanent');
res[37].push('Diet');
res[37].push('Hair coloring');
res[37].push('Straight hair permanent');
res.push([]);
res[38].push('Confessing your love by e-mail');
res[38].push('Confessing your love on the phone');
res[38].push('Confessing your love through an instant messaging app');
res[38].push('Confessing your love at a cafe');
res[38].push('Confessing your love at the beach');
res[38].push('Confessing your love at the movie theater');
res[38].push('Confessing your love at the restaurant');
res.push([]);
res[39].push('Festival');
res[39].push('Barbecue');
res[39].push('Fireworks');
res.push([]);
res[40].push('Parent-teacher communication notebook');
res[40].push('Diary');
res[40].push('Letter');
res[40].push('Cheat sheet');
res[40].push('Class pet journal');
res.push([]);
res[41].push('Office romance');
res[41].push('teacher student romance');
res[41].push('Doctor patient romance');
res[41].push('Boss employee romance');
res[41].push('Brother sister romance');
res[41].push('Romance between cousins');
res[41].push('Romance between a prince/princess and a commoner');
res.push([]);
res[42].push('Body soap');
res[42].push('Soap bar');
res[42].push('Dish detergent');
res[42].push('Laundry detergent');
res[42].push('Shampoo');
res[42].push('Rinse');
res[42].push('Conditioner');
res.push([]);
res[43].push('Grilled meat');
res[43].push('Slow cooked meat');
res[43].push('Kebab');
res[43].push('Hamburg');
res[43].push('Steak');
res.push([]);
res[44].push('Carrot');
res[44].push('Radish');
res[44].push('Lotus root');
res[44].push('Turnip');
res[44].push('Burdock root');
res.push([]);
res[45].push('Blood test');
res[45].push('Urine test');
res[45].push('Stool test');
res[45].push('Tuberculosis screening');
res[45].push('X-rays');
res.push([]);
res[46].push('Abandoned cat');
res[46].push('Abandoned dog');
res[46].push('Heartbroken best friend');
res[46].push('A best friend who failed an entrance exam');
res.push([]);
res[47].push('Aroma therapy oil');
res[47].push('Aromatic candle');
res[47].push('Air freshener');
res[47].push('Air fragrance');
res[47].push('Perfume');
res[47].push('Incense stick');
res[47].push('Mosquito repellent');
res[47].push('Bug spray');
res.push([]);
res[48].push('Sunscreen');
res[48].push('Toner');
res[48].push('Moisturizing cream');
res[48].push('Lip cream');
res[48].push('Face soap');
res[48].push('Foundation');
res.push([]);
res[49].push('Face powder');
res[49].push('Lipstick');
res[49].push('Eye shadow');
res[49].push('Powder blush');
res[49].push('Mascara');
res[49].push('Fake eyelashes');
res.push([]);
res[50].push('Someone careless');
res[50].push('Someone arrogant');
res[50].push('Someone with restless legs syndrome');
res[50].push('Someone unhygienic');
res[50].push('Someone insane');
res[50].push('Someone weird');
res[50].push('Someone stingy');
res[50].push('Someone short tempered');
res[50].push('An attention whore person');
res[50].push('Someone too naive');
res.push([]);
res[51].push('Demon');
res[51].push('Ghost');
res[51].push('Ogre');
res[51].push('Goblin');
res[51].push('God');
res.push([]);
res[52].push('Space');
res[52].push('Sky');
res[52].push('Heaven');
res[52].push('Roof');
res.push([]);
res[53].push('Love');
res[53].push('Friendship');
res[53].push('Trust');
res[53].push('Effort');
res[53].push('Jealousy');
res.push([]);
res[54].push('Light');
res[54].push('Sound');
res[54].push('Heat');
res[54].push('Ultraviolet rays');
res[54].push('Electromagnetic waves');
res[54].push('Air');
res.push([]);
res[55].push('Shooting star');
res[55].push('Sun');
res[55].push('Space');
res[55].push('Satellite');
res[55].push('Cloud');
res.push([]);
res[56].push('Hourglass');
res[56].push('Wristwatch');
res[56].push('Stopwatch');
res[56].push('Pendulum clock');
res[56].push('Wall clock');
res.push([]);
res[57].push('Angel');
res[57].push('Godness');
res[57].push('Elf');
res[57].push('Holy Mother');
res[57].push('Gremlin');
res.push([]);
res[58].push('Sky');
res[58].push('Heaven');
res[58].push('Reincarnation');
res[58].push('Post-mortem');
res[58].push('Previous life');
res[58].push('Hell');
res.push([]);
res[59].push('Hot (weather)');
res[59].push('Thickness');
res[59].push('Hot (thing, person)');
res[59].push('Weight');
res.push([]);
res[60].push('Curiosity');
res[60].push('Mischief');
res[60].push('Phobia');
res[60].push('Politeness');
res[60].push('Kindness');
res.push([]);
res[61].push('Battlefield');
res[61].push('Hell');
res[61].push('Prison');
res[61].push('Abandoned mine');
res.push([]);
res[62].push('Gold');
res[62].push('Silver');
res[62].push('Precious stone');
res[62].push('Money');
res[62].push('Ring (for fingers)');
res[62].push('Picture');
res.push([]);
res[63].push('Jealousy');
res[63].push('admiration (towards...)');
res[63].push('Crush');
res[63].push('Love at first sight');
res[63].push('Paternal/maternal love');
res.push([]);
res[64].push('Oil');
res[64].push('Water');
res[64].push('Soy sauce');
res[64].push('Vinegar');
res[64].push('Chicken stock');
res[64].push('Cooking alcohol');
res.push([]);
res[65].push('Dinosaur');
res[65].push('Beast');
res[65].push('Wolf');
res[65].push('Werewolf');
res.push([]);
res[66].push('Bully');
res[66].push('Quarrel');
res[66].push('Prank');
res[66].push('Dictatorship');
res.push([]);
res[67].push('Trap');
res[67].push('Grave');
res[67].push('Root cellar');
res[67].push('Cave');
res[67].push('Warehouse');
res.push([]);
res[68].push('Hotspring');
res[68].push('Fountain');
res[68].push('Geyser');
res[68].push('Waterfall');
res.push([]);
res[69].push('Fire');
res[69].push('Flame');
res[69].push('Magma');
res[69].push('Lava');
res[69].push('Volcanic ash');
res.push([]);
res[70].push('Cell (biology)');
res[70].push('Atom');
res[70].push('Molecule');
res[70].push('Microorganism');
res.push([]);
res[71].push('To read');
res[71].push('To study');
res[71].push('To learn by heart');
res[71].push('To listen carefully');
res[71].push('Classroom chatter');
res.push([]);
res[72].push('Mirror');
res[72].push('Glass');
res[72].push('Pocket mirror');
res[72].push('Floor mirror');
res[72].push('Mirror sticker');
res.push([]);
res[73].push('Basement');
res[73].push('Tunnel');
res[73].push('Catacombs');
res[73].push('Ditch (infrastructure)');
res.push([]);
res[74].push('Vampire');
res[74].push('Werewolf');
res[74].push('Undead');
res[74].push('Zombie');
res.push([]);
res[75].push('Gambling');
res[75].push('Stock price');
res[75].push('Casino');
res.push([]);
res[76].push('Medicine');
res[76].push('Aspirin');
res[76].push('Laxative');
res[76].push('Nasal spray');
res[76].push('Eye drops');
res[76].push('Alcohol');
res.push([]);
res[77].push('Footbridge');
res[77].push('Escalator');
res[77].push('Elevator');
res[77].push('Roller coaster');
res.push([]);
res[78].push('Anime cosplay');
res[78].push('Animal costume');
res[78].push('Costume');
res.push([]);
res[79].push('Soup');
res[79].push('Smoothie');
res[79].push('Pot-au-feu (French dish)');
res[79].push('Pho (Vietnamese dish)');
res.push([]);
res[80].push('Colored contact lenses');
res[80].push('Sunglasses');
res[80].push('Corrective contact lenses');
res[80].push('Glasses');
res.push([]);
res[81].push('Wheelbarrow');
res[81].push('Electric bicycle');
res[81].push('Mini truck');
res[81].push('Shopping cart/trolley');
res.push([]);
res[82].push('Coin flipping');
res[82].push('Rock-paper-scissors');
res[82].push('Dice');
res.push([]);
res[83].push('Hairpin');
res[83].push('Rubber band');
res[83].push('Hair band');
res[83].push('Scrunchie (for hair)');
res[83].push('Hair clip');
res.push([]);
res[84].push('Clown');
res[84].push('Magician');
res[84].push('Juggler');
res[84].push('Fire breathing');
res.push([]);
res[85].push('Present');
res[85].push('Bento (Japanese lunch box)');
res[85].push('Gift box');
res[85].push('Individually wrapped snacks');
res.push([]);
res[86].push('Helicopter');
res[86].push('Jet aircraft');
res[86].push('Airplane');
res[86].push('Hot air balloon');
res[86].push('UFO');
res[86].push('Drone');
res[86].push('Spaceship');
res[86].push('Orbiter');
res.push([]);
res[87].push('Cityhall');
res[87].push('Post office');
res[87].push('Convenience store');
res[87].push('Supermarket');
res[87].push('Drugstore');
res.push([]);
res[88].push('Yacht');
res[88].push('Sailing ship');
res[88].push('Kayak');
res[88].push('Cruise ship');
res.push([]);
res[89].push('Amateur');
res[89].push('Minor (under 18)');
res[89].push('Brat');
res[89].push('Immature girl');
res[89].push('Immature boy');
res.push([]);
res[90].push('"No drinking"');
res[90].push('"No smoking"');
res[90].push('"No swimming"');
res[90].push('"No fishing"');
res[90].push('"No shoes inside"');
res.push([]);
res[91].push('Bookmark');
res[91].push('Family photo album');
res[91].push('Book cover');
res[91].push('Bookbinding');
return res;
}
